version: '3'
services:
  db:
    image: postgres:14.2-alpine
    container_name: reminder-postgres-14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # ports:
    #   - "5432:5432"
  web:
    build: .
    command: "./bin/rails server"
    env_file:
      - production.env
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - db
      - sidekiq
      - redis
    ports:
    # host:container
      - "3001:3000"

  sidekiq:
    build: .
    command: "./bin/bundle exec sidekiq"
    container_name: reminder-sidekiq
    env_file:
      - production.env
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    container_name: reminder-redis-6.2
    command: redis-server
    ports:
      - "6379:6379"

volumes:
  postgres_data: {}
  app-storage: {}