redis: &redis
  adapter: redis
  url: redis://localhost:6379/1


development: *redis

test:
  adapter: async


production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: docker_reminder_production
